//created on: 24 feb 2023
package rules

import com.sample.Disease;
import com.sample.Symptoms;


rule "Shortness of breath"
    dialect "java"

    when
    	disease: Disease()
        symptom: Symptoms(Shortness_breath == true )
    then
        disease.setHypoxemia(disease.getHypoxemia() + 3);
        disease.setHyperapnea(disease.getHyperapnea() + 2);
        disease.setTachypnea(disease.getTachypnea() + 2);
        disease.setDysnea(disease.getDysnea() + 3);
        disease.setRespiratory_Insufficiency(disease.getRespiratory_Insufficiency() + 3);
        disease.setLung_cancer(disease.getLung_cancer() + 3);
        disease.setCOVID(disease.getCOVID() + 3);
        disease.setPneumonia(disease.getPneumonia() + 3);
        disease.setPulmonary_Embolism(disease.getPulmonary_Embolism() + 3);
        disease.setMalignant_Pleura_Effusion(disease.getMalignant_Pleura_Effusion() + 3);    

end

rule "Rapid breathing"
    dialect "java"

    when
    	disease: Disease()
        symptom: Symptoms(Rapid_Breathing == true )
    then
        disease.setHypoxemia(disease.getHypoxemia() + 3);
        disease.setHyperapnea(disease.getHyperapnea() + 3);
        disease.setTachypnea(disease.getTachypnea() + 3);
        disease.setDysnea(disease.getDysnea() + 3);

end

rule "Wheezing"
    dialect "java"

    when
    	disease: Disease()
        symptom: Symptoms(Wheezing == true )
    then
        disease.setHypoxemia(disease.getHypoxemia() + 2);
        disease.setTachypnea(disease.getTachypnea() + 2);
        disease.setDysnea(disease.getDysnea() + 2);
        disease.setRespiratory_Insufficiency(disease.getRespiratory_Insufficiency() + 1);
        disease.setLung_cancer(disease.getLung_cancer() + 1);
end

rule "Cyanosis"
    dialect "java"

    when
    	disease: Disease()
        symptom: Symptoms(Cyanosis == true )
    then
        disease.setHypoxemia(disease.getHypoxemia() + 3);
        disease.setTachypnea(disease.getTachypnea() + 2);
        disease.setDysnea(disease.getDysnea() + 2);
        disease.setAsthma(disease.getAsthma() + 1);
        disease.setAtelactasis(disease.getAtelactasis() + 1);
end

rule "Headache"
    dialect "java"

    when
    	disease: Disease()
        symptom: Symptoms(Headache == true )
    then
        disease.setHypoxemia(disease.getHypoxemia() + 1);
        disease.setCOVID(disease.getCOVID() + 2);
        disease.setFlu(disease.getFlu() + 2);
        disease.setApnea(disease.getApnea() + 2);
        disease.setCold(disease.getCold() + 1);    

end

rule "Confusion or Disorientation"
    dialect "java"

    when
    	disease: Disease()
        symptom: Symptoms(Confusion_Disorientation == true )
    then
        disease.setHypoxemia(disease.getHypoxemia() + 2);
        disease.setRespiratory_Insufficiency(disease.getRespiratory_Insufficiency() + 2);
        disease.setPneumonia(disease.getPneumonia() + 2);

end

rule "Irregular Heartbeat"
    dialect "java"

    when
    	disease: Disease()
        symptom: Symptoms(Irregular_heartbeat == true )
    then
        disease.setHypoxemia(disease.getHypoxemia() + 2);
        disease.setHyperapnea(disease.getHyperapnea() + 2);
        disease.setTachypnea(disease.getTachypnea() + 2);
        disease.setDysnea(disease.getDysnea() + 2);
        disease.setRespiratory_Insufficiency(disease.getRespiratory_Insufficiency() + 1);    

end

rule "Chest Pain"
    dialect "java"

    when
    	disease: Disease()
        symptom: Symptoms(Chest_pain == true )
    then
        disease.setHypoxemia(disease.getHypoxemia() + 2);
        disease.setRespiratory_Insufficiency(disease.getRespiratory_Insufficiency() + 1);
        disease.setLung_cancer(disease.getLung_cancer() + 3);
        disease.setPneumonia(disease.getPneumonia() + 2);
        disease.setPulmonary_Embolism(disease.getPulmonary_Embolism() + 2);
        disease.setPneumothorax(disease.getPneumothorax() + 2);
end

rule "Fatigue or Weakness"
    dialect "java"

    when
    	disease: Disease()
        symptom: Symptoms(Fatigue_Weakness == true )
    then
        disease.setHypoxemia(disease.getHypoxemia() + 2);
        disease.setHyperapnea(disease.getHyperapnea() + 2);
        disease.setTachypnea(disease.getTachypnea() + 2);
        disease.setDysnea(disease.getDysnea() + 2);
        disease.setRespiratory_Insufficiency(disease.getRespiratory_Insufficiency() + 3);
        disease.setCOVID(disease.getCOVID() + 2);
        disease.setPneumonia(disease.getPneumonia() + 2);
        disease.setApnea(disease.getApnea() + 2);
        disease.setFlu(disease.getFlu() + 3);

end

rule "Dizziness"
    dialect "java"

    when
    	disease: Disease()
        symptom: Symptoms(Dizziness == true )
    then
        disease.setHypoxemia(disease.getHypoxemia() + 2);
        disease.setHyperapnea(disease.getHyperapnea() + 2);
        disease.setDysnea(disease.getDysnea() + 2);

end











